# Generated by Django 6.0.7 on 2026-08-13 16:36

import users.shelf_theme
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email_unique_password_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shelf_theme',
            field=models.JSONField(blank=True, default=users.shelf_theme.default_shelf_theme),
        ),
    ]
