# Generated by Django 6.0.7 on 2026-08-18 15:46

import django.db.models.deletion
import users.models.avatar_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers_user_avatar_preset_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_preset_id',
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('preset', 'Preset (admin)'), ('upload', 'İstifadəçi yükləməsi')], max_length=10)),
                ('image', models.ImageField(upload_to=users.models.avatar_models.avatar_image_path)),
                ('label', models.CharField(blank=True, help_text='Preset adı, məs: Paul', max_length=80)),
                ('subtitle', models.CharField(blank=True, help_text='Kitab adı, məs: Dune', max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_avatars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='profile_avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_by_users', to='users.avatar'),
        ),
        migrations.AddIndex(
            model_name='avatar',
            index=models.Index(fields=['kind', 'is_active', 'sort_order'], name='users_avata_kind_5041a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='avatar',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'preset'), ('owner__isnull', True)), models.Q(('kind', 'upload'), ('owner__isnull', False)), _connector='OR'), name='avatar_kind_owner_consistency'),
        ),
    ]
