# Generated by Django 6.0.7 on 2026-08-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shelf',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='shelf',
            name='status',
            field=models.CharField(choices=[('reading', 'Oxuyuram'), ('finished', 'Bitirdim'), ('want', 'Oxuyacam')], default='want', max_length=20),
        ),
    ]
