# Generated by Django 6.0.7 on 2026-08-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('about', 'Haqqımızda'), ('terms', 'İstifadə şərtləri'), ('community_rules', 'Topluluq qaydaları')], max_length=32, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('document_title', models.CharField(blank=True, max_length=255)),
                ('intro', models.JSONField(blank=True, default=list)),
                ('outro', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platforma səhifəsi',
                'verbose_name_plural': 'Platforma səhifələri',
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='SitePageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('heading', models.CharField(max_length=200)),
                ('paragraphs', models.JSONField(blank=True, default=list)),
                ('items', models.JSONField(blank=True, default=list)),
                ('after', models.JSONField(blank=True, default=list)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.sitepage')),
            ],
            options={
                'verbose_name': 'Səhifə bölməsi',
                'verbose_name_plural': 'Səhifə bölmələri',
                'ordering': ['order', 'id'],
            },
        ),
    ]
