# Generated by Django 6.0.7 on 2026-08-15 17:25

import books.models.author_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=books.models.author_models.author_cover_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(blank=True, choices=[('roman', 'Roman'), ('povest', 'Povest'), ('seir', 'Şeir'), ('esse', 'Esse'), ('usaq', 'Uşaq ədəbiyyatı'), ('epik', 'Epik')], max_length=20),
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.author'),
        ),
    ]
